# Generated by Django 5.2.8 on 2025-11-29 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('references', '0002_alter_referenceitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(blank=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('downtime', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Время простоя техники, дни')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('failure_node', models.ForeignKey(limit_choices_to={'category': 'failure_node'}, on_delete=django.db.models.deletion.PROTECT, related_name='claims_as_failure_node', to='references.referenceitem', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='machines.machine', verbose_name='Машина')),
                ('repair_method', models.ForeignKey(limit_choices_to={'category': 'repair_method'}, on_delete=django.db.models.deletion.PROTECT, related_name='claims_as_repair_method', to='references.referenceitem', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_as_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-failure_date', '-id'],
            },
        ),
    ]
