# Generated by Django 5.2.8 on 2025-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceitem',
            name='category',
            field=models.CharField(choices=[('machine_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steer_axle_model', 'Модель управляемого моста'), ('maintenance_type', 'Вид ТО'), ('failure_node', 'Узел отказа'), ('repair_method', 'Способ восстановления'), ('service_organization', 'Организация, проводившая ТО')], max_length=50, verbose_name='Тип справочника'),
        ),
    ]
