# Generated by Django 5.2.8 on 2025-11-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('references', '0002_alter_referenceitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(blank=True, max_length=100, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='machines.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(limit_choices_to={'category': 'maintenance_type'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_as_type', to='references.referenceitem', verbose_name='Вид ТО')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_as_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('service_organization', models.ForeignKey(blank=True, limit_choices_to={'category': 'service_organization'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_as_org', to='references.referenceitem', verbose_name='Организация, проводившая ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'ordering': ['-maintenance_date', '-id'],
            },
        ),
    ]
