# Generated by Django 5.2.8 on 2025-11-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Зав. № двигателя')),
                ('transmission_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Зав. № ведущего моста')),
                ('steer_axle_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Зав. № управляемого моста')),
                ('contract_number_and_date', models.CharField(blank=True, max_length=255, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(blank=True, max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('options', models.TextField(blank=True, verbose_name='Комплектация (доп. опции)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(limit_choices_to={'category': 'drive_axle_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_drive_axle_model', to='references.referenceitem', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(limit_choices_to={'category': 'engine_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_engine_model', to='references.referenceitem', verbose_name='Модель двигателя')),
                ('machine_model', models.ForeignKey(limit_choices_to={'category': 'machine_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_model', to='references.referenceitem', verbose_name='Модель техники')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('steer_axle_model', models.ForeignKey(limit_choices_to={'category': 'steer_axle_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_steer_axle_model', to='references.referenceitem', verbose_name='Модель управляемого моста')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'category': 'transmission_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_transmission_model', to='references.referenceitem', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['-shipment_date', 'serial_number'],
            },
        ),
    ]
